#define SEC_LEVEL_VIOLET 2
#define SEC_LEVEL_ORANGE 3
#define SEC_LEVEL_AMBER 4
#define SEC_LEVEL_EPSILON 7 // CENTCOM IS ANGY!!!
#define SEC_LEVEL_GAMMA 8 // Oh shit bois
#define SEC_LEVEL_FEDERAL 9 // THE FUCKING FEDS ARE HERE!!!
