name: Check TG Mirror PR for Alliance Edits

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-alliance-edits:
    runs-on: ubuntu-latest

    steps:
    - name: Check PR title for [TG Mirror]
      id: check-title
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        
        if echo "$PR_TITLE" | grep -i '\[TG Mirror\]' > /dev/null; then
          echo "is-tg-mirror=true" >> "$GITHUB_OUTPUT"
        else
          echo "is-tg-mirror=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Stop if not a TG Mirror PR
      if: steps.check-title.outputs.is-tg-mirror == 'false'
      run: |
        echo "Not a [TG Mirror] PR — skipping."
        exit 0

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Нужно для получения diff

    - name: Get list of changed files
      id: changed-files
      uses: tj-actions/changed-files@v46
      with:
        since_last_remote_commit: true

    - name: Detect Alliance Edit Flag
      id: detect-flag
      run: |
        FLAG="// ALLIANCE_EDIT_FLAG"
        MATCH=false
        
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          # Проверим, существует ли файл
          if [ -f "$file" ]; then
            # считается только начало файла (первые 5 строк)
            if head -n 5 "$file" | grep -q "$FLAG"; then
              echo "Файл с кастомным флагом найден: $file"
              MATCH=true
              break
            fi
          fi
        done

        echo "match-found=$MATCH" >> "$GITHUB_OUTPUT"

    - name: Add PR label if needed
      if: steps.detect-flag.outputs.match-found == 'true'
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: conflicts-with-alliance-edits
